-- Gen1→Gen2 Kanto splits (only where Gen1 values ≠ Gen2 values).
-- Generated by scripts/generate-gen2-kanto-splits-seed.mjs
-- Apply after gen1_pokemon / gen1_moves when DB still has shared Gen1+ masks.
-- Fresh reseeds from gen1_pokemon.sql already include these rows.

update moshimo.pokemon set available_generations = 1, updated_at = now() where dex_no = 42 and name_en = 'Golbat' and available_generations = 255;
update moshimo.pokemon set available_generations = 1, updated_at = now() where dex_no = 81 and name_en = 'Magnemite' and available_generations = 511;
update moshimo.pokemon set available_generations = 1, updated_at = now() where dex_no = 82 and name_en = 'Magneton' and available_generations = 511;
update moshimo.pokemon set available_generations = 1, updated_at = now() where dex_no = 95 and name_en = 'Onix' and available_generations = 255;
update moshimo.pokemon set available_generations = 1, updated_at = now() where dex_no = 123 and name_en = 'Scyther' and available_generations = 511;

insert into moshimo.pokemon (dex_no, region_type, name_ja, name_en, category, introduced_generation, available_generations, type1, type2, base_hp, base_attack, base_defense, base_special, base_sp_attack, base_sp_defense, base_speed, ability1_id, ability2_id, hidden_ability_id, gender, is_mega, is_final_evolution, sprite_url) values
(42, 0, 'ゴルバット', 'Golbat', 'normal', 1, 254, 8, 10, 75, 80, 70, NULL, 65, 75, 90, '00000000-0000-4000-8000-000000000039', NULL, '00000000-0000-4000-8000-000000000151', 1, FALSE, FALSE, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png'),
(81, 0, 'コイル', 'Magnemite', 'normal', 1, 510, 4, 17, 25, 35, 70, NULL, 95, 55, 45, '00000000-0000-4000-8000-000000000042', '00000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000148', 0, FALSE, FALSE, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png'),
(82, 0, 'レアコイル', 'Magneton', 'normal', 1, 510, 4, 17, 50, 60, 95, NULL, 120, 70, 70, '00000000-0000-4000-8000-000000000042', '00000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000148', 0, FALSE, TRUE, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png'),
(95, 0, 'イワーク', 'Onix', 'normal', 1, 254, 13, 9, 35, 45, 160, NULL, 30, 45, 70, '00000000-0000-4000-8000-000000000069', '00000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000133', 1, FALSE, FALSE, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png'),
(123, 0, 'ストライク', 'Scyther', 'normal', 1, 510, 12, 10, 70, 110, 80, NULL, 55, 80, 105, '00000000-0000-4000-8000-000000000068', '00000000-0000-4000-8000-000000000101', '00000000-0000-4000-8000-000000000080', 1, FALSE, FALSE, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png')
on conflict (dex_no, region_type, is_mega, name_en, available_generations) do update set
  type1 = excluded.type1,
  type2 = excluded.type2,
  base_special = excluded.base_special,
  is_final_evolution = excluded.is_final_evolution,
  updated_at = now();

-- Copy existing junctions onto Gen2+ rows (learned while shared Gen1+ mask).
insert into moshimo.pokemon_moves (pokemon_id, move_id)
select p_new.id, pm.move_id
from moshimo.pokemon p_old
join moshimo.pokemon_moves pm on pm.pokemon_id = p_old.id
join moshimo.pokemon p_new
  on p_new.dex_no = p_old.dex_no
 and p_new.name_en = p_old.name_en
 and p_new.region_type = p_old.region_type
 and p_new.is_mega = p_old.is_mega
 and (p_new.available_generations & 2) <> 0
where p_old.dex_no in (42, 81, 82, 95, 123)
  and p_old.available_generations = 1
on conflict (pokemon_id, move_id) do nothing;

-- Moves: no Gen1≠Gen2 power/accuracy/PP/type splits detected.
