-- Gen4 physical/special split + Gen4 value changes for Gen1–3 moves.
-- Rows covering Gen1–3 and Gen4+ are split; Gen4+-only rows are updated in place.
-- NULL power / accuracy / pp = unchanged in Gen4 (keep the row's value).
create table if not exists moshimo._seed_gen4_move_values (
  pokeapi_id integer primary key,
  damage_class text not null,
  power integer null,
  accuracy integer null,
  pp integer null
);
truncate table moshimo._seed_gen4_move_values;

insert into moshimo._seed_gen4_move_values (pokeapi_id, damage_class, power, accuracy, pp) values
(1, 'physical', NULL, NULL, NULL),
(2, 'physical', NULL, NULL, NULL),
(3, 'physical', NULL, NULL, NULL),
(4, 'physical', NULL, NULL, NULL),
(5, 'physical', NULL, NULL, NULL),
(6, 'physical', NULL, NULL, NULL),
(7, 'physical', NULL, NULL, NULL),
(8, 'physical', NULL, NULL, NULL),
(9, 'physical', NULL, NULL, NULL),
(10, 'physical', NULL, NULL, NULL),
(11, 'physical', NULL, NULL, NULL),
(12, 'physical', NULL, NULL, NULL),
(13, 'special', NULL, NULL, NULL),
(14, 'status', NULL, NULL, NULL),
(15, 'physical', NULL, NULL, NULL),
(16, 'special', NULL, NULL, NULL),
(17, 'physical', NULL, NULL, NULL),
(18, 'status', NULL, NULL, NULL),
(19, 'physical', 90, NULL, NULL),
(20, 'physical', NULL, NULL, NULL),
(21, 'physical', NULL, NULL, NULL),
(22, 'physical', NULL, NULL, 15),
(23, 'physical', NULL, NULL, NULL),
(24, 'physical', NULL, NULL, NULL),
(25, 'physical', NULL, NULL, NULL),
(26, 'physical', 85, NULL, NULL),
(27, 'physical', NULL, NULL, NULL),
(28, 'status', NULL, NULL, NULL),
(29, 'physical', NULL, NULL, NULL),
(30, 'physical', NULL, NULL, NULL),
(31, 'physical', NULL, NULL, NULL),
(32, 'physical', NULL, NULL, NULL),
(33, 'physical', NULL, NULL, NULL),
(34, 'physical', NULL, NULL, NULL),
(35, 'physical', NULL, NULL, NULL),
(36, 'physical', NULL, NULL, NULL),
(37, 'physical', NULL, NULL, NULL),
(38, 'physical', NULL, NULL, NULL),
(39, 'status', NULL, NULL, NULL),
(40, 'physical', NULL, NULL, NULL),
(41, 'physical', NULL, NULL, NULL),
(42, 'physical', NULL, NULL, NULL),
(43, 'status', NULL, NULL, NULL),
(44, 'physical', NULL, NULL, NULL),
(45, 'status', NULL, NULL, NULL),
(46, 'status', NULL, NULL, NULL),
(47, 'status', NULL, NULL, NULL),
(48, 'status', NULL, NULL, NULL),
(49, 'special', NULL, NULL, NULL),
(50, 'status', NULL, 80, NULL),
(51, 'special', NULL, NULL, NULL),
(52, 'special', NULL, NULL, NULL),
(53, 'special', NULL, NULL, NULL),
(54, 'status', NULL, NULL, NULL),
(55, 'special', NULL, NULL, NULL),
(56, 'special', NULL, NULL, NULL),
(57, 'special', NULL, NULL, NULL),
(58, 'special', NULL, NULL, NULL),
(59, 'special', NULL, NULL, NULL),
(60, 'special', NULL, NULL, NULL),
(61, 'special', NULL, NULL, NULL),
(62, 'special', NULL, NULL, NULL),
(63, 'special', NULL, NULL, NULL),
(64, 'physical', NULL, NULL, NULL),
(65, 'physical', NULL, NULL, NULL),
(66, 'physical', NULL, NULL, NULL),
(67, 'physical', NULL, NULL, NULL),
(68, 'physical', NULL, NULL, NULL),
(69, 'physical', NULL, NULL, NULL),
(70, 'physical', NULL, NULL, NULL),
(71, 'special', NULL, NULL, 25),
(72, 'special', NULL, NULL, 15),
(73, 'status', NULL, NULL, NULL),
(74, 'status', NULL, NULL, NULL),
(75, 'physical', NULL, NULL, NULL),
(76, 'special', NULL, NULL, NULL),
(77, 'status', NULL, NULL, NULL),
(78, 'status', NULL, NULL, NULL),
(79, 'status', NULL, NULL, NULL),
(80, 'special', 90, NULL, NULL),
(81, 'status', NULL, NULL, NULL),
(82, 'special', NULL, NULL, NULL),
(83, 'special', NULL, NULL, NULL),
(84, 'special', NULL, NULL, NULL),
(85, 'special', NULL, NULL, NULL),
(86, 'status', NULL, NULL, NULL),
(87, 'special', NULL, NULL, NULL),
(88, 'physical', NULL, NULL, NULL),
(89, 'physical', NULL, NULL, NULL),
(90, 'physical', NULL, NULL, NULL),
(91, 'physical', 80, NULL, NULL),
(92, 'status', NULL, NULL, NULL),
(93, 'special', NULL, NULL, NULL),
(94, 'special', NULL, NULL, NULL),
(95, 'status', NULL, 60, NULL),
(96, 'status', NULL, NULL, NULL),
(97, 'status', NULL, NULL, NULL),
(98, 'physical', NULL, NULL, NULL),
(99, 'physical', NULL, NULL, NULL),
(100, 'status', NULL, NULL, NULL),
(101, 'special', NULL, NULL, NULL),
(102, 'status', NULL, NULL, NULL),
(103, 'status', NULL, NULL, NULL),
(104, 'status', NULL, NULL, NULL),
(105, 'status', NULL, NULL, 5),
(106, 'status', NULL, NULL, NULL),
(107, 'status', NULL, NULL, NULL),
(108, 'status', NULL, NULL, NULL),
(109, 'status', NULL, NULL, NULL),
(110, 'status', NULL, NULL, NULL),
(111, 'status', NULL, NULL, NULL),
(112, 'status', NULL, NULL, NULL),
(113, 'status', NULL, NULL, NULL),
(114, 'status', NULL, NULL, NULL),
(115, 'status', NULL, NULL, NULL),
(116, 'status', NULL, NULL, NULL),
(117, 'physical', NULL, NULL, NULL),
(118, 'status', NULL, NULL, NULL),
(119, 'status', NULL, NULL, NULL),
(120, 'physical', NULL, NULL, NULL),
(121, 'physical', NULL, NULL, NULL),
(122, 'physical', NULL, NULL, NULL),
(123, 'special', NULL, NULL, NULL),
(124, 'special', NULL, NULL, NULL),
(125, 'physical', NULL, NULL, NULL),
(126, 'special', NULL, NULL, NULL),
(127, 'physical', NULL, NULL, NULL),
(128, 'physical', NULL, NULL, NULL),
(129, 'special', NULL, NULL, NULL),
(130, 'physical', NULL, NULL, NULL),
(131, 'physical', NULL, NULL, NULL),
(132, 'physical', NULL, NULL, NULL),
(133, 'status', NULL, NULL, NULL),
(134, 'status', NULL, NULL, NULL),
(135, 'status', NULL, NULL, NULL),
(136, 'physical', 100, NULL, NULL),
(137, 'status', NULL, NULL, NULL),
(138, 'special', NULL, NULL, NULL),
(139, 'status', NULL, NULL, NULL),
(140, 'physical', NULL, NULL, NULL),
(141, 'physical', NULL, NULL, NULL),
(142, 'status', NULL, NULL, NULL),
(143, 'physical', NULL, NULL, NULL),
(144, 'status', NULL, NULL, NULL),
(145, 'special', NULL, NULL, NULL),
(146, 'physical', NULL, NULL, NULL),
(147, 'status', NULL, NULL, NULL),
(148, 'status', NULL, 100, NULL),
(149, 'special', NULL, NULL, NULL),
(150, 'status', NULL, NULL, NULL),
(151, 'status', NULL, NULL, NULL),
(152, 'physical', NULL, NULL, NULL),
(153, 'physical', NULL, NULL, NULL),
(154, 'physical', NULL, NULL, NULL),
(155, 'physical', NULL, NULL, NULL),
(156, 'status', NULL, NULL, NULL),
(157, 'physical', NULL, NULL, NULL),
(158, 'physical', NULL, NULL, NULL),
(159, 'status', NULL, NULL, NULL),
(160, 'status', NULL, NULL, NULL),
(161, 'special', NULL, NULL, NULL),
(162, 'physical', NULL, NULL, NULL),
(163, 'physical', NULL, NULL, NULL),
(164, 'status', NULL, NULL, NULL),
(165, 'physical', NULL, NULL, NULL),
(166, 'status', NULL, NULL, NULL),
(167, 'physical', NULL, NULL, NULL),
(168, 'physical', NULL, NULL, NULL),
(169, 'status', NULL, NULL, NULL),
(170, 'status', NULL, NULL, NULL),
(171, 'status', NULL, NULL, NULL),
(172, 'physical', NULL, NULL, NULL),
(173, 'special', NULL, NULL, NULL),
(174, 'status', NULL, NULL, NULL),
(175, 'physical', NULL, NULL, NULL),
(176, 'status', NULL, NULL, NULL),
(177, 'special', NULL, NULL, NULL),
(178, 'status', NULL, NULL, NULL),
(179, 'physical', NULL, NULL, NULL),
(180, 'status', NULL, NULL, NULL),
(181, 'special', NULL, NULL, NULL),
(182, 'status', NULL, NULL, NULL),
(183, 'physical', NULL, NULL, NULL),
(184, 'status', NULL, NULL, NULL),
(185, 'physical', NULL, NULL, NULL),
(186, 'status', NULL, NULL, NULL),
(187, 'status', NULL, NULL, NULL),
(188, 'special', NULL, NULL, NULL),
(189, 'special', NULL, NULL, NULL),
(190, 'special', NULL, NULL, NULL),
(191, 'status', NULL, NULL, NULL),
(192, 'special', 120, NULL, NULL),
(193, 'status', NULL, NULL, NULL),
(194, 'status', NULL, NULL, NULL),
(195, 'status', NULL, NULL, NULL),
(196, 'special', NULL, NULL, NULL),
(197, 'status', NULL, NULL, NULL),
(198, 'physical', NULL, NULL, NULL),
(199, 'status', NULL, NULL, NULL),
(200, 'physical', 120, NULL, NULL),
(201, 'status', NULL, NULL, NULL),
(202, 'special', NULL, NULL, 10),
(203, 'status', NULL, NULL, NULL),
(204, 'status', NULL, NULL, NULL),
(205, 'physical', NULL, NULL, NULL),
(206, 'physical', NULL, NULL, NULL),
(207, 'status', NULL, NULL, NULL),
(208, 'status', NULL, NULL, NULL),
(209, 'physical', NULL, NULL, NULL),
(210, 'physical', NULL, NULL, NULL),
(211, 'physical', NULL, NULL, NULL),
(212, 'status', NULL, NULL, NULL),
(213, 'status', NULL, NULL, NULL),
(214, 'status', NULL, NULL, NULL),
(215, 'status', NULL, NULL, NULL),
(216, 'physical', NULL, NULL, NULL),
(217, 'physical', NULL, NULL, NULL),
(218, 'physical', NULL, NULL, NULL),
(219, 'status', NULL, NULL, NULL),
(220, 'status', NULL, NULL, NULL),
(221, 'physical', NULL, NULL, NULL),
(222, 'physical', NULL, NULL, NULL),
(223, 'physical', NULL, NULL, NULL),
(224, 'physical', NULL, NULL, NULL),
(225, 'special', NULL, NULL, NULL),
(226, 'status', NULL, NULL, NULL),
(227, 'status', NULL, NULL, NULL),
(228, 'physical', NULL, NULL, NULL),
(229, 'physical', NULL, NULL, NULL),
(230, 'status', NULL, NULL, NULL),
(231, 'physical', NULL, NULL, NULL),
(232, 'physical', NULL, NULL, NULL),
(233, 'physical', NULL, NULL, NULL),
(234, 'status', NULL, NULL, NULL),
(235, 'status', NULL, NULL, NULL),
(236, 'status', NULL, NULL, NULL),
(237, 'special', NULL, NULL, NULL),
(238, 'physical', NULL, NULL, NULL),
(239, 'special', NULL, NULL, NULL),
(240, 'status', NULL, NULL, NULL),
(241, 'status', NULL, NULL, NULL),
(242, 'physical', NULL, NULL, NULL),
(243, 'special', NULL, NULL, NULL),
(244, 'status', NULL, NULL, NULL),
(245, 'physical', NULL, NULL, NULL),
(246, 'special', NULL, NULL, NULL),
(247, 'special', NULL, NULL, NULL),
(248, 'special', NULL, NULL, NULL),
(249, 'physical', 40, NULL, NULL),
(250, 'special', NULL, NULL, NULL),
(251, 'physical', NULL, NULL, NULL),
(252, 'physical', NULL, NULL, NULL),
(253, 'special', NULL, NULL, NULL),
(254, 'status', NULL, NULL, 20),
(255, 'special', NULL, NULL, NULL),
(256, 'status', NULL, NULL, NULL),
(257, 'special', NULL, NULL, NULL),
(258, 'status', NULL, NULL, NULL),
(259, 'status', NULL, NULL, NULL),
(260, 'status', NULL, NULL, NULL),
(261, 'status', NULL, NULL, NULL),
(262, 'status', NULL, NULL, NULL),
(263, 'physical', NULL, NULL, NULL),
(264, 'physical', NULL, NULL, NULL),
(265, 'physical', NULL, NULL, NULL),
(266, 'status', NULL, NULL, NULL),
(267, 'status', NULL, NULL, NULL),
(268, 'status', NULL, NULL, NULL),
(269, 'status', NULL, NULL, NULL),
(270, 'status', NULL, NULL, NULL),
(271, 'status', NULL, NULL, NULL),
(272, 'status', NULL, NULL, NULL),
(273, 'status', NULL, NULL, NULL),
(274, 'status', NULL, NULL, NULL),
(275, 'status', NULL, NULL, NULL),
(276, 'physical', NULL, NULL, NULL),
(277, 'status', NULL, NULL, NULL),
(278, 'status', NULL, NULL, NULL),
(279, 'physical', NULL, NULL, NULL),
(280, 'physical', NULL, NULL, NULL),
(281, 'status', NULL, NULL, NULL),
(282, 'physical', NULL, NULL, NULL),
(283, 'physical', NULL, NULL, NULL),
(284, 'special', NULL, NULL, NULL),
(285, 'status', NULL, NULL, NULL),
(286, 'status', NULL, NULL, NULL),
(287, 'status', NULL, NULL, NULL),
(288, 'status', NULL, NULL, NULL),
(289, 'status', NULL, NULL, NULL),
(290, 'physical', NULL, NULL, NULL),
(291, 'physical', 80, NULL, NULL),
(292, 'physical', NULL, NULL, NULL),
(293, 'status', NULL, NULL, NULL),
(294, 'status', NULL, NULL, NULL),
(295, 'special', NULL, NULL, NULL),
(296, 'special', NULL, NULL, NULL),
(297, 'status', NULL, NULL, NULL),
(298, 'status', NULL, NULL, NULL),
(299, 'physical', NULL, NULL, NULL),
(300, 'status', NULL, NULL, NULL),
(301, 'physical', NULL, NULL, NULL),
(302, 'physical', NULL, NULL, NULL),
(303, 'status', NULL, NULL, NULL),
(304, 'special', NULL, NULL, NULL),
(305, 'physical', NULL, NULL, NULL),
(306, 'physical', NULL, NULL, NULL),
(307, 'special', NULL, NULL, NULL),
(308, 'special', NULL, NULL, NULL),
(309, 'physical', NULL, NULL, NULL),
(310, 'physical', NULL, NULL, NULL),
(311, 'special', NULL, NULL, NULL),
(312, 'status', NULL, NULL, NULL),
(313, 'status', NULL, NULL, NULL),
(314, 'special', NULL, NULL, NULL),
(315, 'special', NULL, NULL, NULL),
(316, 'status', NULL, NULL, NULL),
(317, 'physical', NULL, NULL, NULL),
(318, 'special', NULL, NULL, NULL),
(319, 'status', NULL, NULL, NULL),
(320, 'status', NULL, NULL, NULL),
(321, 'status', NULL, NULL, NULL),
(322, 'status', NULL, NULL, NULL),
(323, 'special', NULL, NULL, NULL),
(324, 'special', NULL, NULL, NULL),
(325, 'physical', NULL, NULL, NULL),
(326, 'special', NULL, NULL, NULL),
(327, 'physical', NULL, NULL, NULL),
(328, 'physical', NULL, NULL, NULL),
(329, 'special', NULL, NULL, NULL),
(330, 'special', NULL, NULL, NULL),
(331, 'physical', NULL, NULL, NULL),
(332, 'physical', NULL, NULL, NULL),
(333, 'physical', NULL, NULL, NULL),
(334, 'status', NULL, NULL, NULL),
(335, 'status', NULL, NULL, NULL),
(336, 'status', NULL, NULL, NULL),
(337, 'physical', NULL, NULL, NULL),
(338, 'special', NULL, NULL, NULL),
(339, 'status', NULL, NULL, NULL),
(340, 'physical', NULL, NULL, NULL),
(341, 'special', NULL, NULL, NULL),
(342, 'physical', NULL, NULL, NULL),
(343, 'physical', NULL, NULL, NULL),
(344, 'physical', NULL, NULL, NULL),
(345, 'special', NULL, NULL, NULL),
(346, 'status', NULL, NULL, NULL),
(347, 'status', NULL, NULL, NULL),
(348, 'physical', 90, NULL, NULL),
(349, 'status', NULL, NULL, NULL),
(350, 'physical', NULL, NULL, NULL),
(351, 'special', NULL, NULL, NULL),
(352, 'special', NULL, NULL, NULL),
(353, 'special', NULL, NULL, NULL),
(354, 'special', NULL, NULL, NULL);

insert into moshimo.moves (
  id, pokeapi_id, name_ja, name_en, type_id, damage_class, power, accuracy, pp,
  priority, description, effect_category, effect_meta, effect_code,
  introduced_generation, available_generations
)
select
  md5('gen4-split:' || m.id::text)::uuid,
  m.pokeapi_id, m.name_ja, m.name_en, m.type_id,
  case when m.damage_class = 'status' then m.damage_class else v.damage_class end,
  coalesce(v.power, m.power), coalesce(v.accuracy, m.accuracy), coalesce(v.pp, m.pp),
  m.priority, m.description, m.effect_category, m.effect_meta, m.effect_code,
  m.introduced_generation, m.available_generations & ~7
from moshimo.moves m
join moshimo._seed_gen4_move_values v on v.pokeapi_id = m.pokeapi_id
where (m.available_generations & 8) <> 0
  and (m.available_generations & 7) <> 0
  and (
    (m.damage_class <> 'status' and m.damage_class <> v.damage_class)
    or (v.power is not null and m.power is distinct from v.power)
    or (v.accuracy is not null and m.accuracy is distinct from v.accuracy)
    or (v.pp is not null and m.pp is distinct from v.pp)
  )
on conflict (pokeapi_id, available_generations) do nothing;

update moshimo.moves m
set available_generations = m.available_generations & 7,
    updated_at = now()
from moshimo._seed_gen4_move_values v
where v.pokeapi_id = m.pokeapi_id
  and (m.available_generations & 8) <> 0
  and (m.available_generations & 7) <> 0
  and (
    (m.damage_class <> 'status' and m.damage_class <> v.damage_class)
    or (v.power is not null and m.power is distinct from v.power)
    or (v.accuracy is not null and m.accuracy is distinct from v.accuracy)
    or (v.pp is not null and m.pp is distinct from v.pp)
  );

update moshimo.moves m
set damage_class = case when m.damage_class = 'status' then m.damage_class else v.damage_class end,
    power = coalesce(v.power, m.power),
    accuracy = coalesce(v.accuracy, m.accuracy),
    pp = coalesce(v.pp, m.pp),
    updated_at = now()
from moshimo._seed_gen4_move_values v
where v.pokeapi_id = m.pokeapi_id
  and (m.available_generations & 8) <> 0
  and (m.available_generations & 7) = 0
  and (
    (m.damage_class <> 'status' and m.damage_class <> v.damage_class)
    or (v.power is not null and m.power is distinct from v.power)
    or (v.accuracy is not null and m.accuracy is distinct from v.accuracy)
    or (v.pp is not null and m.pp is distinct from v.pp)
  );

drop table if exists moshimo._seed_gen4_move_values;
